"use client";

import { useActionState } from "react";
import { updateOrganization, inviteOrganizationMember, removeOrganizationMember } from "@/actions/organizations";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";

export function OrganizationSettingsForm({ organization }: { organization: { id: string; name: string; logo_url: string | null; primary_color: string; custom_domain: string | null } }) {
  const [state, action, pending] = useActionState(updateOrganization, undefined);
  return <form action={action} className="grid gap-4 rounded-[var(--radius-md)] border border-border bg-surface p-5"><input type="hidden" name="organization_id" value={organization.id} /><Field label="Organization name" htmlFor="name"><Input id="name" name="name" defaultValue={organization.name} required /></Field><Field label="Logo URL" htmlFor="logo_url"><Input id="logo_url" name="logo_url" defaultValue={organization.logo_url ?? ""} placeholder="https://.../logo.png" /></Field><Field label="Brand color" htmlFor="primary_color"><Input id="primary_color" name="primary_color" type="color" defaultValue={organization.primary_color} className="h-10 w-16 p-1" /></Field><Field label="Custom domain (optional)" htmlFor="custom_domain"><Input id="custom_domain" name="custom_domain" defaultValue={organization.custom_domain ?? ""} placeholder="learn.example.com" /></Field>{state?.error && <p className="text-sm text-danger">{state.error}</p>}{state?.success && <p className="text-sm text-success">Branding saved.</p>}<Button type="submit" disabled={pending}>{pending ? "Saving…" : "Save branding"}</Button></form>;
}

export function InviteMemberForm({ organizationId }: { organizationId: string }) { const [state, action, pending] = useActionState(inviteOrganizationMember, undefined); return <form action={action} className="grid gap-4 rounded-[var(--radius-md)] border border-border bg-surface p-5 sm:grid-cols-2"><input type="hidden" name="organization_id" value={organizationId} /><Field label="Full name" htmlFor="full_name"><Input id="full_name" name="full_name" required /></Field><Field label="Email" htmlFor="email"><Input id="email" name="email" type="email" required /></Field><Field label="Role" htmlFor="role"><select id="role" name="role" defaultValue="student" className="w-full rounded-[var(--radius-sm)] border border-border bg-surface px-3.5 py-2.5 text-sm"><option value="student">Student</option><option value="instructor">Instructor</option><option value="admin">Administrator</option></select></Field><div className="flex items-end"><Button type="submit" disabled={pending}>{pending ? "Sending…" : "Invite member"}</Button></div>{state?.error && <p className="text-sm text-danger sm:col-span-2">{state.error}</p>}{state?.success && <p className="text-sm text-success sm:col-span-2">Invite sent and membership added.</p>}</form>; }

export function RemoveMemberButton({ organizationId, userId }: { organizationId: string; userId: string }) { const [state, action, pending] = useActionState(removeOrganizationMember, undefined); return <form action={action}><input type="hidden" name="organization_id" value={organizationId} /><input type="hidden" name="user_id" value={userId} /><button className="text-xs font-medium text-danger" disabled={pending}>{pending ? "Removing…" : "Remove"}</button>{state?.error && <span className="ml-2 text-xs text-danger">{state.error}</span>}</form>; }
