import Link from "next/link";
import { ArrowRight, Award, PlayCircle, Sparkles, UsersRound } from "lucide-react";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { HeroSlideshow } from "@/components/marketing/hero-slideshow";

export default function Home() {
  return <MarketingShell><main>
    <section className="home-hero"><div className="marketing-container hero-grid"><div><p className="eyebrow">Education for the work ahead</p><h1>Make room for your <em>next chapter.</em></h1><p className="lede">Inkstructs helps ambitious people and teams build practical skills through clear, supportive, instructor-led learning.</p><div className="hero-actions"><Link href="/courses" className="button">Explore courses <ArrowRight size={17} /></Link><Link href="/about" className="text-link">Why Inkstructs <ArrowRight size={16} /></Link></div><div className="hero-proof"><span><UsersRound size={17} /> Live cohorts</span><span><Award size={17} /> Certificates</span><span><PlayCircle size={17} /> Flexible access</span></div></div><div className="hero-visual"><HeroSlideshow /><div className="floating-note"><Sparkles size={17} /><span><strong>Learning that sticks</strong><small>One useful step at a time.</small></span></div></div></div></section>
    <section className="marketing-container intro-section"><div><p className="eyebrow">A better way to learn</p><h2>Practical knowledge, made personal.</h2></div><p>From first principles to finished projects, our programs give you the structure, support, and confidence to keep going.</p></section>
    <section className="marketing-container benefit-section"><div className="benefit-copy"><p className="eyebrow">Why learners choose Inkstructs</p><h2>Turn curiosity into capability.</h2><p>Whether you are starting fresh, changing direction, or helping your team level up, our learning experiences are built around progress you can see and use.</p><Link href="/services" className="text-link">See how we help <ArrowRight size={16} /></Link></div><div className="benefit-list"><div><strong>01</strong><span><b>Learn with a plan</b>Clear weekly structure keeps momentum high.</span></div><div><strong>02</strong><span><b>Practice what matters</b>Projects connect learning to real work.</span></div><div><strong>03</strong><span><b>Keep the support</b>Guidance, feedback, and a community around you.</span></div></div></section>
    <section className="stats-band"><div className="marketing-container stats-grid"><div><strong>01</strong><span>Learn from experienced instructors</span></div><div><strong>02</strong><span>Practice with real-world projects</span></div><div><strong>03</strong><span>Track your progress in one place</span></div></div></section>
    <section className="marketing-container platform-section"><div><p className="eyebrow">For schools & platforms</p><h2>Bring a complete learning dashboard to your community.</h2><p>Inkstructs can help schools, academies, and education platforms launch a polished learning experience under their own program. We support installation, configuration, course setup, and team onboarding.</p><Link href="/contact" className="button">Talk about your platform <ArrowRight size={17} /></Link></div><div className="platform-points"><div><strong>01</strong><span><b>Install</b>Connect the dashboard to your website or platform.</span></div><div><strong>02</strong><span><b>Configure</b>Shape courses, roles, cohorts, and certificates around your model.</span></div><div><strong>03</strong><span><b>Launch with confidence</b>Get practical guidance for your team and learners.</span></div></div></section>
    <section className="marketing-container home-cta"><p className="eyebrow">Your next move</p><h2>Start with one good decision.</h2><Link href="/apply" className="button">Apply now <ArrowRight size={17} /></Link></section>
  </main></MarketingShell>;
}
