import Link from "next/link";
import { ArrowRight, Award, PlayCircle, Sparkles, UsersRound } from "lucide-react";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { HeroSlideshow } from "@/components/marketing/hero-slideshow";

export default function Home() {
  return <MarketingShell><main>
    <section className="home-hero"><div className="marketing-container hero-grid"><div><p className="eyebrow">Your learning workspace</p><h1>Learn with a clear path to your <em>next chapter.</em></h1><p className="lede">Access your organization’s courses, cohorts, assignments, progress, and certificates in one focused learning dashboard.</p><div className="hero-actions"><Link href="/login" className="button">Sign in to dashboard <ArrowRight size={17} /></Link></div><div className="hero-proof"><span><UsersRound size={17} /> Instructor support</span><span><Award size={17} /> Certificates</span><span><PlayCircle size={17} /> Flexible access</span></div></div><div className="hero-visual"><HeroSlideshow /><div className="floating-note"><Sparkles size={17} /><span><strong>Learning that sticks</strong><small>One useful step at a time.</small></span></div></div></div></section>
    <section className="marketing-container intro-section"><div><p className="eyebrow">A better way to learn</p><h2>Practical knowledge, made personal.</h2></div><p>From first principles to finished projects, our programs give you the structure, support, and confidence to keep going.</p></section>
    <section className="marketing-container benefit-section"><div className="benefit-copy"><p className="eyebrow">Why learners choose Inkstructs</p><h2>Turn curiosity into capability.</h2><p>Your organization’s learning space is built around visible progress, practical work, and the support you need to keep moving.</p><Link href="/login" className="text-link">Open my dashboard <ArrowRight size={16} /></Link></div><div className="benefit-list"><div><strong>01</strong><span><b>Learn with a plan</b>Clear weekly structure keeps momentum high.</span></div><div><strong>02</strong><span><b>Practice what matters</b>Projects connect learning to real work.</span></div><div><strong>03</strong><span><b>Keep the support</b>Guidance, feedback, and a community around you.</span></div></div></section>
    <section className="stats-band"><div className="marketing-container stats-grid"><div><strong>01</strong><span>Learn from experienced instructors</span></div><div><strong>02</strong><span>Practice with real-world projects</span></div><div><strong>03</strong><span>Track your progress in one place</span></div></div></section>
    <section className="marketing-container platform-section"><div><p className="eyebrow">Your organization’s workspace</p><h2>Everything you need to keep learning moving.</h2><p>Sign in to view the courses and learning tools enabled by your organization. Your content, progress, and permissions stay within this dashboard.</p><Link href="/login" className="button">Enter dashboard <ArrowRight size={17} /></Link></div><div className="platform-points"><div><strong>01</strong><span><b>Courses</b>See the learning assigned to you.</span></div><div><strong>02</strong><span><b>Progress</b>Pick up where you left off.</span></div><div><strong>03</strong><span><b>Support</b>Connect with your instructors and organization.</span></div></div></section>
    <section className="marketing-container home-cta"><p className="eyebrow">Ready when you are</p><h2>Continue your learning journey.</h2><Link href="/login" className="button">Sign in <ArrowRight size={17} /></Link></section>
  </main></MarketingShell>;
}
